// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7NSl9mT7gkuBNN0HSdgDnrah9nl24E7o',
    appId: '1:593462834623:web:48fe04bfd11bf8d3289d0a',
    messagingSenderId: '593462834623',
    projectId: 'pig-killer-riders',
    authDomain: 'pig-killer-riders.firebaseapp.com',
    storageBucket: 'pig-killer-riders.firebasestorage.app',
    measurementId: 'G-2Q4VM1QM7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7aGL6muoaASrP9Gck5WUfhiSNZI4B_fU',
    appId: '1:593462834623:android:762b7666d52ad703289d0a',
    messagingSenderId: '593462834623',
    projectId: 'pig-killer-riders',
    storageBucket: 'pig-killer-riders.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqMpiczwroeuMRC_VpeuZGAD_HrRpu6hw',
    appId: '1:593462834623:ios:75408261f4e5af1a289d0a',
    messagingSenderId: '593462834623',
    projectId: 'pig-killer-riders',
    storageBucket: 'pig-killer-riders.firebasestorage.app',
    iosBundleId: 'com.example.pigKillerRiders',
  );
}
